Entrevistas Ivan | Mauricio - Colaboracao iUFBA | SIC
iUFBA/iufba.github.io pull request #5
Opened 2017-03-06 20:35 UTC by FormigTeen

Grupo de alunos de Seminário de Introdução ao Curso em Ciência da Computação 2016.2:
    Grupo:Anita Borg
    Integrantes:Vinícius Drumond, Matheus Freitas, Dimitri Marinho, João Gondim e João Blanes.
Trabalho de  Seminário de alunos no tópico 5: Avaliação Curricular e Formatura.

2017-03-08 15:48 UTC, gildasio requested changes
No mais, só fazer essas modificações citadas e está tudo certo.

Para o texto sobre avaliação curricular, recomendo tentar fazer algo como um infográfico ou um fluxograma bem arrumado para ficar mais ilustrativo ao público.

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-entrevista-mauricio.md
> +title: Entrevista - Prof. Maurício Pamplona
Acredito que seria melhor especificar como "Entrevista com Prof. Maurício Pamplona sobre o Curso de Ciências da Computação"

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-entrevista-mauricio.md
> +Entrevistador - Como você avalia o curso de ciência da computação e sua grade curricular na formação do aluno?
Recomendo que dê uma olhada sobre markdown para que possa organizar um pouco melhor o visual do texto, algo como:

**Entrevistador**: Como você avalia o curso ...
**Prof. Maurício**: Eu diria que é a formação mais teórica ...

Segue um link que recomendo: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-entrevista-ivan.md
> +title: Entrevista - Prof. Ivan Machado
Acredito que seria melhor especificar como "Entrevista com Prof. Ivan Machado sobre o Curso de Ciências da Computação"

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-entrevista-ivan.md
> +Entrevistador - Como você avalia a grade curricular do curso de ciência de computação em comparação a das outras universidades, por exemplo, a da Unifacs,que fica em localizada também em Salvador/BA
Recomendo olhar esse link: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Nele tem um manual da sintaxe do markdown. Bom utilizar para melhorar um pouco a visualização das informações no texto.

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-avalicacao-curricular-formatura.md
> +categories: blog
Certeza que esse texto se trata de um simples post para o blog do iUFBA? Não seria algo para uma outra categoria, como estudos?

2017-03-08 15:48 UTC, gjuniioor commented on _posts/2017-03-06-avalicacao-curricular-formatura.md
> +  • Cumprir as disciplinas obrigatórias definidas no currículo do curso.
Recomendo olhar esse link: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Nele tem um manual da sintaxe markdown - utilizada pelo Jekyll e nesses arquivos. Utilizando melhor dela fica mais organizado o texto, por exemplo, nesse caso das listas, bom colocar no formato do markdown de fato.

2017-03-09 09:17 UTC, FormigTeen commented
Alterações Realizadas com base no Review. Tentei deixar o Guia de Avaliação em Ordened, porém, tive problemas em manter a sequência e no Stack OverFlow só encontrei soluções adicionando o texto ou o código que quebra a sequência em CodeBlocks mas isso quebraria o MK. Espero que esteja tudo ok, Vlw!

2017-03-26 18:12 UTC, FormigTeen commented
@gjuniioor , Alterações Realizadas.

2023-09-05 19:23 UTC, closed without merging